# Set default engine to `XeLaTeX` and make `silent` mode the default
$pdf_mode = 5;
$silent = 1;

# When `nomencl` package is used, invoke `MakeIndex` to create nomenclature
# file
add_cus_dep('nlo','nls',0,'nlo2nls');
sub nlo2nls {
    system("makeindex \"$_[0].nlo\" -s nomencl.ist -o \"$_[0].nls\"");
}
